Do not ignore case of options.
zeek/btest pull request #79
Opened 2022-12-07 10:35 UTC by bbannier

Options in our ini file are usually interpreted as environment variables which are case-sensitive on many platforms, e.g., `http_proxy` and `HTTP_PROXY` are different environment variables. Our config parser reads in environment variables as configuration value defaults, but the `ConfigParser` used under the covers prefers to treat them as case-insensitve in its default ini file dialect.

With this patch we now override this behavior of our config parser and treat config keys as case-sensitive. This yields the expected behavior for environment variables, but also is a API-breaking change for our ini files where we preserve case as well.

Closes #75.

2022-12-08 00:10 UTC, ckreibich requested changes
Fwiw I'm fine with backward-incompatible changes. If we move the next release to 1.0.0 that signals this, too. I do think we should introduce a `NEWS` file so we can call such changes out, though. You're welcome to start it now, or we can do it later, as we roll the release.

2022-12-08 00:30 UTC, timwoj commented on testing/tests/env-var-casing.test
> +# %TEST-DOC: Validates that env vars are case-sensitive; this is a regression test for #75.
Almost every test (or every test?) I've seen starts the commands with a `#`.

2022-12-08 08:23 UTC, bbannier commented on testing/tests/env-var-casing.test
> +# %TEST-EXEC: touch .btest.cfg
Thanks for catching this, this was a completely bogus attempt to put a default `btest.cfg` in place. I added the file you suggested (with an additional var) to also check casing of vars in the cfg file. I also made the coding changes you pointed out to make that work.

2022-12-08 08:24 UTC, bbannier commented on testing/tests/env-var-casing.test
> +# %TEST-DOC: Validates that env vars are case-sensitive; this is a regression test for #75.
I habitually put BTest instructions behind `#` since otherwise my editor often detects some bogus file type and reports uninteresting syntax issues. Using `#` usually leads it to detect some shell.

2022-12-09 21:37 UTC, ckreibich commented on testing/tests/env-var-casing.test
> +# %TEST-DOC: Validates that env vars are case-sensitive; this is a regression test for #75.
That's a good point, I hadn't considered that. You technically only need the comment strings when running the file through an interpreter, like with `bash %INPUT`. Case closed.

2022-12-09 22:08 UTC, ckreibich approved these changes

2022-12-09 22:10 UTC, merged